name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Verify Java version
        run: java -version

      - name: Build with Maven
        working-directory: MyApiApplication
        run: mvn clean package

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: MyApiApplication/target/*.jar

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: MyApiApplication/target/

      - name: Verify JAR exists
        run: ls -la MyApiApplication/target/

      - name: Build Docker image
        working-directory: MyApiApplication
        run: docker build -t myapi:latest .

      - name: Run Docker container
        run: docker run -d -p 8080:8080 myapi:latest
