name: CI/CD Pipeline
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
    - name: Set up JDK 23
      uses: actions/setup-java@v1
      with:
        java-version: '23'
 
    - name: Build with Maven
      run: mvn clean package
 
    - name: Run Unit Tests
      run: mvn test
 
    - name: Run Functional Tests
      run: mvn verify
 
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
 
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/MyApiApplication:latest .
 
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/MyApiApplication:latest
 
    - name: Create Git Tag
      id: tag
      run: echo "::set-output name=tag::$(echo ${GITHUB_REF##*/}-$(date +%Y%m%d%H%M%S))"
 
    - name: Push Git Tag
      run: git tag ${{ steps.tag.outputs.tag }} && git push origin ${{ steps.tag.outputs.tag }}
